[phases.setup]
nixPkgs = ["dotnet-sdk_10"]
nixpkgsArchive = "5c4b5e54b429fb1b151e5aa5f7c92d2820680fc4"
aptPkgs = ["libgssapi-krb5-2"]

[phases.install]
cmds = ["dotnet restore Backend/Wesal.slnx"]

[phases.build]
nixpkgsArchive = "5c4b5e54b429fb1b151e5aa5f7c92d2820680fc4"
cmds = ["dotnet publish Backend/src/Wesal.API/Wesal.API.csproj -c Release -o out --no-restore"]

[start]
cmd = "./out/Wesal.API"